Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -19,7 +19,7 @@ steps:
         if [ "$BRANCH_NAME" = "main" ]; then
           echo "Main Called"
           if [ -d "environments/dev" ]; then
-            cd environments/$BRANCH_NAME
+            cd environments/dev
             terraform init
           else
             echo "Not Found"
@@ -47,9 +47,15 @@ steps:
     args:
       - "-c"
       - |
-        if [ -d "environments/$BRANCH_NAME/" ]; then
-          cd environments/$BRANCH_NAME
-          terraform plan
+        if [ "$BRANCH_NAME" = "main" ]; then
+          echo "Main Called"
+          if [ -d "environments/dev" ]; then
+            cd environments/dev
+            terraform plan
+          else
+            echo "Not Found"
+            exit 1
+          fi
         else
           for dir in environments/*/
           do
